title:              "Izzy's Easy Business"
tagline:            "The joy of winning strategies - That easy!"
email:              "your-email@example.com"
description:        "An easy guide to successful global business"
author:             "Isabel Lee"
baseurl:            "/"
url:                "https://easybiz.kr"
locale:             "ko_KR"
thumbnail:          "/img/blog_thumbnail.png"

# Social Profiles
twitter_username:
instagram_username:
facebook_username:
linkedin_username:  

# Build settings
markdown:           kramdown
permalink:          /:title
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-paginate
